version: '2'
services:
  app:
    build: .
    command: npm run app
    environment:
      NEFIT_SERIAL_NUMBER: ${NEFIT_SERIAL_NUMBER}
      NEFIT_ACCESS_KEY: ${NEFIT_ACCESS_KEY}
      NEFIT_PASSWORD: ${NEFIT_PASSWORD}
      MQTT_URL: ${MQTT_URL}
      MQTT_USERNAME: ${MQTT_USERNAME}
      MQTT_PASSWORD: ${MQTT_PASSWORD}
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
