#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  repository: cprinse/nefit-easy-mqtt-bridge
  tag: "1.3"
  pullPolicy: IfNotPresent

env:
  TZ: UTC
  NEFIT_SERIAL_NUMBER: "720924484"
  NEFIT_ACCESS_KEY: "SLLKwHuBXHbJVrT9"
  NEFIT_PASSWORD: "7Q4mXNc477"
  MQTT_URL: mqtt://mosquitto:1883
  MQTT_USERNAME: admin
  MQTT_PASSWORD: admin
  PUBLISH_TO_SEPERATE_TOPICS: 'true'
  TOPIC_PREFIX: nefit/living_room
  AUTODISCOVER_NAME: woonkamer
  POLL_DELAY: 30000
  NODE_OPTIONS: "--unhandled-rejections=strict"


service:
  main:
    ports:
      http:
        port: 8200

ingress:
  main:
    enabled: false

persistence:
  config:
    enabled: false
  source:
    enabled: false
  backups:
    enabled: false

probes:
  liveness:
    enabled: false
  readiness:
    enabled: false
  startup:
    enabled: false